[FEATURE] Pre and post import eventDispatchers
TYPO3-extensions/news pull request #1850
Opened 2022-09-15 14:08 UTC by Zillion01

Resolves #1849

2022-09-16 06:41 UTC, georgringer requested changes

2022-09-16 06:41 UTC, georgringer commented on Classes/Event/NewsPostImportEvent.php
> +
please add `declare(strict_types=1);`

2022-09-16 06:41 UTC, georgringer commented on Classes/Event/NewsPreImportEvent.php
> +
please add `declare(strict_types=1);`

2022-09-16 06:41 UTC, georgringer commented on Classes/Event/NewsPostImportEvent.php
> +    /**
all those comments can be removed, also in other event

2022-09-19 13:13 UTC, merged

2022-09-20 09:10 UTC, Zillion01 commented
Thanks a lot

2022-09-20 09:12 UTC, georgringer commented
thanks to you ;)